// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using PortalTi.Api.Data;  // <-- Agregado

#nullable disable

namespace PortalTi.Api.Migrations
{
    [DbContext(typeof(PortalTiContext))]
    [Migration("20250802140439_UsuariosYActivos")]
    partial class UsuariosYActivos : Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthUser", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<byte[]>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");
                b.Property<byte[]>("PasswordSalt")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");
                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("AuthUsers");
            });

            modelBuilder.Entity("NominaUsuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Apellido")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Departamento")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Rut")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("NominaUsuarios");
            });

            modelBuilder.Entity("PortalTi.Api.Models.Activo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int?>("Cantidad")
                    .HasColumnType("int");
                b.Property<string>("Capacidad")
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Categoria")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("DiscosJson")
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Estado")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Imei")
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Marca")
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Modelo")
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Nombre")
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("NombreEquipo")
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Pulgadas")
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Ram")
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Serie")
                    .HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("Activos");
            });
#pragma warning restore 612, 618
        }
    }
}
